#=============================================================================
#===== This playbook assumes a defined ansible_inventory and /etc/hostfile ===
#===== It changes the hostnames und uploads the /etc/hostfile to all servers =
#=============================================================================

- name: Wait for instances boot and install software packages
  gather_facts: False
  hosts: servers
  become: true
  tasks:
  - name: Set a hostname
    ansible.builtin.hostname:
     name: "{{inventory_hostname}}"

  - name: Copy the etc/host-file to all servers
    copy:
      src: "{{ssh_files_path}}/{{cluster_name}}/hosts"
      dest: /etc/
      mode: '0777'
    become: true